version: '3'

services:
  microservice:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: myparcelcom/microservice:v6-dev
    working_dir: /opt/app
    environment:
      - APP_DOMAIN=$APP_DOMAIN
      - APP_LOG_LEVEL=$APP_LOG_LEVEL
      - XDEBUG_IDE_KEY=$XDEBUG_IDE_KEY
      - XDEBUG_PORT=$XDEBUG_PORT
    ports:
      - $APP_PORT:443
    volumes:
      - .:/opt/app
      - composercache:/.composer/cache
    networks:
      - default
      - micronet

  redis:
    image: redis:3.2
    volumes:
      - redisdata:/data
    networks:
      - default

volumes:
  redisdata:
    driver: local
  composercache:
    driver: local

networks:
  default:
    driver: bridge
  micronet:
    external: true
