version: '3'

services:
  microservice:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        REGISTRY: ${REGISTRY}
    image: myparcelcom/microservice:v7-dev
    working_dir: /opt/app
    env_file: .env.xdebug
    environment:
      - APP_ENV=$APP_ENV
      - APP_DOMAIN=$APP_DOMAIN
      - APP_LOG_LEVEL=$APP_LOG_LEVEL
    ports:
      - $APP_PORT:443
    volumes:
      - .:/opt/app
      - composercache:/.composer/cache
    networks:
      - default
      - micronet

  redis:
    image: redis:3.2
    volumes:
      - redisdata:/data
    networks:
      - default

volumes:
  redisdata:
    driver: local
  composercache:
    driver: local

networks:
  default:
    driver: bridge
  micronet:
    external: true
