apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: ${CIRCLE_PROJECT_REPONAME}-autoscaler
  namespace: ${NS}
  labels:
    app: ${CIRCLE_PROJECT_REPONAME}-autoscaler
    revision: ${CIRCLE_SHA1}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${CIRCLE_PROJECT_REPONAME}
  minReplicas: ${REPLICAS}
  maxReplicas: ${REPLICAS_MAX}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: ${AVERAGE_CPU_UTILIZATION_PERCENTAGE}
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ${CIRCLE_PROJECT_REPONAME}
  namespace: ${NS}
spec:
  minAvailable: ${PDB_MIN_AVAILABLE}
  selector:
    matchLabels:
      app: ${CIRCLE_PROJECT_REPONAME}
