apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${CIRCLE_PROJECT_REPONAME}
  namespace: ${NS}
  labels:
    app: ${CIRCLE_PROJECT_REPONAME}
    revision: ${CIRCLE_SHA1}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${CIRCLE_PROJECT_REPONAME}
  template:
    metadata:
      labels:
        app: ${CIRCLE_PROJECT_REPONAME}
        revision: ${CIRCLE_SHA1}
    spec:
      containers:
        - name: ${CIRCLE_PROJECT_REPONAME}
          image: myparcelcom/microservice:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 443
          envFrom:
            - configMapRef:
                name: ${CIRCLE_PROJECT_REPONAME}-config
            - secretRef:
                name: ${CIRCLE_PROJECT_REPONAME}-secrets
      imagePullSecrets:
        - name: docker-hub
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
