apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${CIRCLE_PROJECT_REPONAME}
  namespace: ${NS}
  annotations:
    sidecar.jaegertracing.io/inject: "true"
  labels:
    app: ${CIRCLE_PROJECT_REPONAME}
    revision: ${CIRCLE_SHA1}
    build: "${CIRCLE_BUILD_NUM}"
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: ${CIRCLE_PROJECT_REPONAME}
  template:
    metadata:
      labels:
        app: ${CIRCLE_PROJECT_REPONAME}
        revision: ${CIRCLE_SHA1}
        build: "${CIRCLE_BUILD_NUM}"
    spec:
      containers:
        - name: ${CIRCLE_PROJECT_REPONAME}
          image: myparcelcom/${IMAGE_NAME}:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 443
          envFrom:
            - configMapRef:
                name: ${CIRCLE_PROJECT_REPONAME}-config
            - secretRef:
                name: ${CIRCLE_PROJECT_REPONAME}-secrets
          resources:
            requests:
              memory: ${RESOURCES_REQ_MEM}
              cpu: ${RESOURCES_REQ_CPU}
      imagePullSecrets:
        - name: docker-hub
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
