apiVersion: v1
kind: Secret
metadata:
  name: ${CIRCLE_PROJECT_REPONAME}-secrets
  namespace: ${NS}
data:
  MYPARCELCOM_API_SECRET: ${MYPARCELCOM_API_SECRET}
  ADDRESS_SERVICE_SECRET: ${ADDRESS_SERVICE_SECRET}
