version: '2.1'
jobs:
  test:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - checkout
      - run:
          name: Setup environment variables
          command: |
            ./mp.sh
      - run:
          name: Login to AWS ECR
          command: |
            aws ecr get-login-password --region "${AWS_DEFAULT_REGION}" | \
              docker login --username AWS --password-stdin "${ECR_REGISTRY}"
      - run:
          name: Setup dependencies
          command: |
            ./mp.sh up
            ./mp.sh composer install
            ./mp.sh schema bundle
      - run:
          name: Run tests
          command: |
            if [ "${CIRCLE_PROJECT_REPONAME}" != "microservice-skeleton" ]; then
              ./mp.sh test --no-coverage
            else
              ./mp.sh test skeleton --no-coverage
            fi

  build:
    docker:
      - image: myparcelcom/build-utils
        auth:
          username: ${DOCKER_CLOUD_USER}
          password: ${DOCKER_CLOUD_PASSWORD}
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Setup environment variables
          command: |
            ./mp.sh
      - run:
          name: Authenticate AWS ECR
          command: ecr-login
      - run:
          name: Deploy to docker
          command: |
            IMAGE_NAME="${ECR_REGISTRY}/myparcelcom/${CIRCLE_PROJECT_REPONAME}:$(image_tag --next-gen)"

            docker build \
              -t ${IMAGE_NAME} \
              --build-arg CARRIER_SPEC_BRANCH=$(spec_ref) \
              --build-arg REGISTRY=${ECR_REGISTRY} \
              -f docker/app/Dockerfile .
            docker push ${IMAGE_NAME}

workflows:
  test:
    jobs:
      - test:
          context: [ "aws" ]
          filters:
            branches:
              ignore:
                - master
                - develop

  build_and_deploy:
    jobs:
      - test:
          context: [ "aws" ]
          filters:
            branches:
              only:
                - master
                - develop
            tags:
              only: /^v\d+\.\d+\.\d+-?\d*$/
      - build:
          context: [ "aws", "docker_cloud" ]
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - develop
            tags:
              only: /^v\d+\.\d+\.\d+-?\d*$/
