<?php

declare(strict_types=1);

namespace MyParcelCom\Microservice\Tests\Unit\ServiceRates;

use MyParcelCom\Microservice\Tests\TestCase;

class ServiceRateTransformerTest extends TestCase {
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
